### ISSUE TITLE
Inconsistent delay

### ISSUE THREAD

**Issue by Hyphen-ated** [ChTBoner/snes_input_display#14]
I tried setting this up with SNI and an fxpak pro on a SNES, and I'm getting a lot of inconsistency in how much latency the tool has.

Here is a test recording where I slash my sword in LTTP twenty times: https://i.imgur.com/0izi65O.mp4

My footage shows snes_input_display displaying the B button being pressed before the sword slash begins. So that means my capture device (a GV-USB2) has more delay than this tool. That's okay. I can compensate for that if there's a consistent offset. The problem is the number of frames of difference between the two is quite variable. Since my video capture is not itself jittery, the inconsistency must be on the snes_input_display side.

Here are twenty measurements of how many frames apart the tool and the game capture are:
3,3,2,1,4,5,2,2,2,2,2,2,4,4,2,2,2,2,2,2

They're usually two frames apart but they can be as close as one frame or as far as five frames. This is very undesirable -- the reason I want to use this tool is so I can look back at my footage and see exactly what my inputs were on any given frame. Maybe if there were an occasional slight bit of jitter that's something I could just deal with, but as it stands the tool is not really useful to me at all.

other details: I'm using OBS and windows 10. I built the tool from commit d43bfb2

**Comment by ChTPwner** [comment]
Hi, thanks for the feedback.
I am on vacation right now so I can't take a look at it without my wife asking for a divorce 😅
I'll be back next week.

In the meantime, would you mind checking with Skarnik's ButtonMash if you have similar behaviour ?
https://github.com/Skarsnik/Button-Mash/releases

**Comment by ChTPwner** [comment]
Also, If you are looking for a lot precision, have you on looked at setting up a RetroSpy?

**Comment by Hyphen-ated** [comment]
I just tried out ButtonMash over qusb2snes with the same test and got these results:
4,4,5,5,5,6,6,4,5,5,4,6,2,2,3,4,4,5,5,6
not really any better. I wonder if the jitter is on the fxpak's end?

I'm aware the retrospy exists. If I could get a good solution without adding any more hardware that would be ideal, since I already have way too many cables around my desk.

**Comment by ChTPwner** [comment]
I suggest you go on SNI's discord (If you haven't already) and ask your questions there. They are very knowledgeable about these things and should be able to help you and answer your questions.

https://discord.com/invite/7jETMegg

The are many things from the FxPak, to your Usb ports, that can add latency and cause issues.

**Comment by Hyphen-ated** [comment]
Sure, thanks for the pointer

**Comment by Hyphen-ated** [comment]
The jitter is caused by the fxpak pro saving sram to the SD card every 250 ms, which is a process that takes 80ms to run and which stops the fxpak from responding over USB during that time. jsd1982 told me to try editing the LTTP header to say the ramsize is 0, which tricks the fxpak into skipping this process. When I do that, then snes_input_display running over qusb2snes has rock-solid consistent latency. Bingo! unfortunately this trick makes the game unplayable. there needs to be some kind of fix in the fxpak firmware to really solve this problem.

**Comment by Hyphen-ated** [comment]
I feel like the most appropriate solution right now is for input display applications to warn in their readmes that if you connect to a snes flashcart over USB, there will be several frames of jitter.
